- include_vars: roles/bootstrap/jails/vars/main.yml

- name: Ensure Path
  file:
    path: "{{ jail_dir }}api-gateway{{ item }}"
    state: directory
  loop:
    - "{{ gateway_dir }}/"
    - "{{ gateway_dir }}/config"
    - "/usr/local/etc/rc.d/"

- name: Download DIEM-API
  get_url:
    url: "{{ gateway_release }}"
    dest: "{{ jail_dir }}api-gateway{{ gateway_dir }}/apis"
    mode: 0700

- name: Gen Config
  template:
    src: diem.toml.j2
    dest: "{{ jail_dir }}api-gateway{{ gateway_dir }}/config/diem.toml"
    mode: 0600

- name: Copy as Service
  template:
    src: gateway.j2
    dest: "{{ jail_dir }}api-gateway/usr/local/etc/rc.d/apis"

- name: Enable Search Service
  community.general.sysrc:
    name: apis_enable
    value: "YES"
    jail: api-gateway
