- name: Compile BBR Kernel
  hosts: deploy
  roles:
    - role: bootstrap/bbr
  tags:
    - never

- name: Deploy Bootstrap
  hosts: deploy
  roles:
    - bootstrap/env
    - bootstrap/jails

- name: Deploy Postgres
  hosts: postgres
  roles:
    - bootstrap/postgres

- name: Deploy Nginx
  hosts: deploy
  roles:
    - scaffolding/nginx

- name: Deploy Acme-Sh
  hosts: acme-sh
  environment:
    CF_Token: "{{ CF_Token }}"
    CF_Account_ID: "{{ CF_Account_ID }}"
    CF_Zone_ID: "{{ CF_Zone_ID }}"
  roles:
    - scaffolding/acme

- name: Deploy Trojan
  hosts: trojan
  roles:
    - application/trojan
  tags:
    - trojan