- hosts: deploy
  roles:
    # - bootstrap/env
    - bootstrap/jails
    - scaffolding/nginx

- hosts: acme-sh
  environment:
    CF_Token: "{{ CF_Token }}"
    CF_Account_ID: "{{ CF_Account_ID }}"
    CF_Zone_ID: "{{ CF_Zone_ID }}"
  roles:
    - scaffolding/acme