all:
  hosts:
    crown:
      ansible_connection: local
    acme:
      ansible_connection: jail
      jail_ip: 10.5.0.13
    trojan-go:
      ansible_connection: jail
      jail_ip: 10.5.0.15
    nginx:
      ansible_connection: jail
      jail_ip: 10.5.0.86

  children:
    deploy:
      hosts:
        crown:

    jails:
      hosts:
        acme-sh:
        trojan-go:
        nginx:
