all:
  hosts:
    crown:
    acme-sh:
      jail_ip: 10.5.0.10
    trojan:
      jail_ip: 10.5.0.15
    gateway:
      jail_ip: 10.5.0.86

    deploy:
      hosts:
        crown:

    jails:
      hosts:
        acme-sh:
        gateway:
        trojan:
