all:
  hosts:
    crown:
      ansible_connection: local
    acme:
      ansible_connection: jail
    trojan:
      ansible_connection: jail
    nginx:
      ansible_connection: jail
    postgres:
      ansible_connection: jail

  children:
    deploy:
      hosts:
        crown:

    jails:
      hosts:
        acme:
        trojan:
        nginx:
        postgres:
