all:
  hosts:
    crown:
      ansible_connection: local
    acme-sh:
      ansible_connection: jail
    trojan:
      ansible_connection: jail
    nginx:
      ansible_connection: jail
    postgres:
      ansible_connection: jail
    vaultwarden:
      ansible_connection: jail
    search-api:
      ansible_connection: jail

  children:
    deploy:
      hosts:
        crown:

    jails:
      hosts:
        acme-sh:
        trojan:
        nginx:
        postgres:
        vaultwarden:
        search-api:
