- name: Download trojan-go
  get_url:
    url: "{{ trojan_release }}"
    dest: /tmp/trojan-go.zip

- name: Ensure Trojan Path
  file:
    path: "{{ trojan_dir }}"
    state: directory

- name: Unzip trojan-go
  shell: unzip /tmp/trojan-go.zip -d {{ trojan_dir }}

