- include: get_trojan.yml

- block:
  - include: ws_path.yml
  - include: setup.yml
  - name: Configure trojan-go
    template:
      src: server.json.j2
      dest: "{{ trojan_dir }}/config/server.json"

- name: Disable Cron
  service:
    name: cron
    enabled: no