- name: Download trojan-go
  get_url:
    url: "{{ trojan_release }}"
    dest: /tmp/trojan-go.zip

- name: Unzip trojan-go
  unarchive:
    src: /tmp/trojan-go.zip
    dest: "{{ trojan_dir }}"
    remote_src: yes

- block:
  - include: ws_path.yml

  - name: Configure trojan-go
    template:
      src: server.json.j2
      dest: "{{ trojan_dir }}/config/server.json"