- name: Random Path List
  set_fact:
    tr_paths: "{{ tr_paths|default([]) + [lookup('password', '/dev/null chars=ascii_letters length=8')] }}"
  loop: [1,2,3,4]

- name: Random Password
  set_fact:
    tr_password: "{{ lookup('password', '/dev/null chars=ascii_letters,digits length=15') }}"

- name: debug
  debug:
    msg:
    - "{{ tr_paths }}"
    - "{{ tr_password }}"