- name: Install NGINX Inside Jail
  pkgng:
    name: nginx
    jail: nginx
    state: present

- include_vars: bootstrap/jails/vars/main.yml

- name: Copy NGINX Configuration
  vars:
    trojan_server: "{{ lookup('env', 'TROJAN_HOST') }}"
  template:
    src: nginx.conf.j2
    dest: "{{ jail_dir }}nginx/usr/local/etc/nginx/nginx.conf"