- name: Install NGINX Inside Jail
  pkgng:
    name: nginx
    jail: nginx
    state: present

- include_vars: roles/bootstrap/jails/vars/main.yml

- name: Copy NGINX Configuration
  vars:
    trojan_server: "{{ lookup('env', 'TROJAN_HOST') }}"
  template:
    src: nginx.conf.j2
    dest: "{{ jail_dir }}nginx/usr/local/etc/nginx/nginx.conf"

- name: Enable NGINX at Boot
  community.general.sysrc:
    name: nginx_enable
    value: "YES"
    jail: "nginx"

- name: Restart NGINX
  shell: "jexec nginx service nginx restart"