- name: Install NGINX Inside Jail
  local_action:
    module: pkgng
    name: nginx
    jail: nginx
    state: present

- name: Copy NGINX Configuration
  vars:
    trojan_server: "{{ lookup('env', 'TROJAN_HOST') }}"
  template:
    src: nginx.conf.j2
    dest: /usr/local/etc/nginx/nginx.conf