- name: Set Domain as Fact
  vars:
    acme_domain: "{{ item | upper }}_HOST"
  set_fact:
    real_domain: "{{ lookup('env', acme_domain) }}"

- name: Generate Certificate
  shell: "~/.acme.sh/acme.sh --issue --dns dns_cf --server letsencrypt -d {{ real_domain }}"

- name: Create Directory
  file:
    path: "/root/certs/{{ real_domain }}"
    state: directory

- name: Install Certificate
  shell: "~/.acme.sh/acme.sh --install-cert -d {{ real_domain }} --key-file /root/certs/{{ real_domain }}/priv.key --fullchain-file /root/certs/{{ real_domain }}/fullchain.cer"