- include_vars: roles/bootstrap/jails/vars/main.yml

- name: Download Acme-sh
  get_url:
    url: https://get.acme.sh
    dest: "/tmp/acme.sh"
    mode: '0700'

- name: Run Acme-sh
  shell: /tmp/acme.sh

- name: Delete Acme-sh
  file:
    path: /tmp/acme.sh
    state: absent