- include_vars: roles/bootstrap/jails/vars/main.yml

- name: Download Acme-sh
  get_url:
    url: https://get.acme.sh
    dest: "{{ jail_dir }}/acme-sh/tmp/acme.sh"
    mode: '0700'

- name: Run Acme-sh
  shell: "jexec acme-sh /tmp/acme.sh"

- name: Delete Acme-sh
  file:
    path: "{{ jail_dir }}/acme-sh/tmp/acme.sh"
    state: absent

- name: Install curl
  pkgng:
    name: curl
    jail: acme-sh
    state: present